# Generated by Django 2.2.5 on 2019-09-26 06:33

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='SetupInventoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_category_code', models.PositiveSmallIntegerField()),
                ('inventory_category_name', models.CharField(max_length=256)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SetupVendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='SetupInventoryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(default='', max_length=256)),
                ('inventory_name', models.CharField(max_length=256)),
                ('description', models.TextField(default='')),
                ('inventory_category_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartsetup.SetupInventoryCategory')),
            ],
        ),
    ]
