# Generated by Django 2.2.5 on 2019-09-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0003_auto_20190910_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/profilepix/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, upload_to='images/signature/'),
        ),
    ]
