# Generated by Django 2.2.5 on 2019-10-02 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartsetup', '0004_auto_20191002_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupclients',
            name='account_officer',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setupclients',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='setupclients',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
