# Generated by Django 2.2.5 on 2019-09-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0004_auto_20190914_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='job_description',
        ),
    ]
