# Generated by Django 2.2.5 on 2019-10-07 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0005_auto_20191002_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField(verbose_name='Date')),
                ('receipt_number', models.PositiveIntegerField(default=100)),
                ('bill_to', models.CharField(blank=True, default='', max_length=256)),
                ('pay_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('transfer', 'Transfer'), ('draft', 'Draft')], default='Cheque', max_length=50)),
                ('total_amount', models.FloatField(default=0)),
                ('cash_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Account Name')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupClients', verbose_name='Client Name')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('unit_price', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('revenue_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Account Name')),
            ],
        ),
    ]
