# Generated by Django 2.2.5 on 2019-10-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0007_receiptdetails_receipt_main_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmain',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='receiptdetails',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
