# Generated by Django 2.2.6 on 2019-10-29 07:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0009_auto_20191008_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptdetails',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='receiptdetails',
            name='revenue_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Revenue Account'),
        ),
        migrations.AlterField(
            model_name='receiptmain',
            name='bill_to',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Issued To'),
        ),
        migrations.AlterField(
            model_name='receiptmain',
            name='cash_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Cash Account'),
        ),
        migrations.AlterField(
            model_name='receiptmain',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupClients', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='receiptmain',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Receipt Date/Time'),
        ),
        migrations.CreateModel(
            name='ExpenseMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Receipt Date/Time')),
                ('voucher_number', models.PositiveIntegerField(default=100)),
                ('payee', models.CharField(blank=True, default='', max_length=256, verbose_name='Issued To')),
                ('description', models.TextField(default='')),
                ('pay_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('transfer', 'Transfer'), ('draft', 'Draft')], default='Cheque', max_length=50)),
                ('total_amount', models.FloatField(default=0)),
                ('cash_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Cash Account')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=256)),
                ('unit_price', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('expense_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Revenue Account')),
                ('expense_main_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartsetup.ExpenseMain')),
            ],
        ),
    ]
