# Generated by Django 2.2.6 on 2019-11-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0011_auto_20191101_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartnoteitems',
            old_name='sub_category_code',
            new_name='sub_category',
        ),
    ]
