# Generated by Django 2.2.6 on 2019-11-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0012_auto_20191101_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmain',
            name='bill_to',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Received from'),
        ),
    ]
