# Generated by Django 2.2.6 on 2019-11-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0013_auto_20191104_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartnoteitems',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='chartnoteitems',
            name='sub_category_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='smartsetup.ChartSubCategory'),
        ),
    ]
