# Generated by Django 2.2.6 on 2019-11-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0014_auto_20191104_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartnoteitems',
            old_name='sub_category_code',
            new_name='sub_category',
        ),
    ]
