# Generated by Django 2.2.6 on 2019-11-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0015_auto_20191104_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptdetails',
            name='crebit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems'),
        ),
        migrations.AddField(
            model_name='receiptmain',
            name='Debit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems'),
        ),
    ]
