# Generated by Django 2.2.6 on 2019-11-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0016_auto_20191105_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptdetails',
            old_name='crebit_account',
            new_name='credit_account',
        ),
    ]
