# Generated by Django 2.2.6 on 2019-11-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0017_auto_20191105_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartnoteitems',
            name='sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='noteitems', to='smartsetup.ChartSubCategory'),
        ),
        migrations.AlterField(
            model_name='receiptmain',
            name='date',
            field=models.DateTimeField(verbose_name='Receipt Date/Time'),
        ),
    ]
